# ⚑ Site - Basics
# Site name
name: "Pastels"

# Site logo (partial-URL relative to /img/)
logo: "logo/pastels-logo.png"

# Site sub-title
subtitle: "A pastel-y and creamy Jekyll theme."

# A short description for your site
description: "Handcrafted with &\#10084; by Rishabh Rao"





# ⚑ Site - Advanced
social:
  # Author's Twitter handle
  twitter: "rishabhsrao"

  # Author's Github handle
  github: "rishabhsrao"

  # Author's Facebook handle
  facebook: "rishabhsrao"





# ⚑ Jekyll configuration
markdown: redcarpet
pygments: true
