# ⚑ Site - Basics
# Site title
title: "Pastels"

# Site author
author: "Rishabh Rao"

# Site logo (partial-URL relative to /img/)
logo: "logo/pastels-logo.png"

# Site sub-title
subtitle: "A pastel-y and creamy Jekyll theme."

# A short description for the site
description: "Handcrafted with &hearts; by Rishabh Rao"





# ⚑ Site - Advanced
# Social media
social:
  # Author's Twitter handle
  twitter: "rishabhsrao"

  # Author's Github handle
  github: "rishabhsrao"

  # Author's Facebook handle
  facebook: "rishabhsrao"





# ⚑ Jekyll configuration
markdown: redcarpet
pygments: true
